---
- name: "{{ 'Deploying' if action=='create' else 'Removing' }} Workload"
  hosts: localhost
  vars_files:
    - "{{ my_vars_dir | mandatory }}/my_vars.yml"
  connection: local
  tasks:
  - name: "Registering bastion host"
    add_host:
      groups: remote
      hostname: "bastion.{{ guid }}{{ subdomain_base_suffix }}"

- hosts: remote
  remote_user: "{{ remote_user|d('ec2-user') }}"
  vars_files:
    - "{{ my_vars_dir | mandatory }}/my_vars.yml"
    - "{{ my_vars_dir | mandatory }}/ocp{{ ocp_version }}_vars.yml"
  tasks:
  - block:
    - name: "Checking connection with cluster"
      shell: "oc status"
      register: oc_status
      ignore_errors: yes
    - name: "Copying local Kubeconfig to bastion [4.x]"
      copy:
        src: "{{ output_dir }}/{{ env_type }}_{{ guid }}_kubeconfig"
        dest: "/home/ec2-user/.kube/config"
      when: ocp_version == '4' and oc_status.rc != 0
    - name: "Create kubeconfig"
      file:
        path: "{{ item.name }}"
        mode: 0777
        owner: ec2-user
        state: "{{ item.state }}"
      loop:
        - name: "/home/ec2-user/.kube"
          state: directory
        - name: "/home/ec2-user/.kube/config"
          state: touch
      become: yes
      when: ocp_version == '3' and oc_status.rc != 0
    - name: "Logging in [3.x]"
      shell: "oc login -u {{ admin_user  | default('opentlc-mgr') }} -p {{ admin_password | default('r3dh4t1!') }} https://master.{{ guid }}{{ subdomain_base_suffix }} --insecure-skip-tls-verify=true --config /home/ec2-user/.kube/config"
      when: ocp_version == '3' and oc_status.rc != 0

  - name: "Including secrets and workload variables..."
    include_vars: "{{ item }}"
    loop:
      - "../secret.yml"
      - "./workload_vars/{{ workload }}.yml"

  - when: ocp_version == '3'
    delegate_to: localhost
    block:
    - name: "Checking if workload exists [3.x]..."
      stat:
        path: "{{ agnosticd_home }}/ansible/roles/ocp-workload-{{ workload }}"
      register: workload_exists
    - set_fact:
        workload_name: "ocp-workload-{{ workload }}"
      when: workload_exists.stat.exists
    - fail:
        msg: "Workload does not exist for specified OCP version."
      when: not workload_exists.stat.exists

  - when: ocp_version == '4'
    delegate_to: localhost
    block:
    - name: "Checking if workload exists [4.x]..."
      stat:
        path: "{{ agnosticd_home }}/ansible/roles/ocp4-workload-{{ workload }}"
      register: workload_exists
    - name: "Checking if shared workload exists [4.x]..."
      stat:
        path: "{{ agnosticd_home }}/ansible/roles/ocp-workload-{{ workload }}"
      register: shared_workload_exists
      when: not workload_exists.stat.exists
    - set_fact:
        workload_name: "ocp4-workload-{{ workload }}"
      when: workload_exists.stat.exists
    - set_fact:
        workload_name: "ocp-workload-{{ workload }}"
      when: not workload_exists.stat.exists and shared_workload_exists.stat.exists
    - fail:
        msg: "Workload does not exist for specified OCP version."
      when: not workload_exists.stat.exists and not shared_workload_exists.stat.exists

  - include_role:
      name: "{{ workload_name }}"
    vars:
      ACTION: "{{ action }}"
      ansible_ssh_private_key_file: "{{ output_dir }}/{{ guid }}key"
      ansible_user: ec2-user
      playbook_dir: "{{ agnosticd_home }}"
      hosts: remote
      ansible_python_interpreter: "{{ '/opt/virtualenvs/k8s-wload-migration/bin/python' if ocp_version == '3' else '/opt/virtualenvs/k8s/bin/python' }}"
