---
- hosts: localhost
  connection: local
  tasks:

  - name: "Reading cluster information file"
    set_fact:
      ocp4_info:
        ocp4_guid: "{{ lookup('ini', 'guid section=OCP4 file=cluster.info') }}"
        ocp4_domain: "{{ lookup('ini', 'domain section=OCP4 file=cluster.info') | regex_replace('^\\.', '') }}"
        ocp4_ssh_user: "{{ lookup('ini', 'student_name section=OCP4 file=cluster.info') }}"
        ocp4_bastion: "{{ lookup('ini', 'bastion section=OCP4 file=cluster.info') }}"
        ocp4_password: "{{ ocp4_password }}"

  - set_fact:
      bookbag_repo: "https://github.com/konveyor/labs.git"
      bookbag_dir: "/home/{{ ansible_user }}/lab-instructions"
      bookbag_build_dir: "oadp/bookbag"

  - name: "Building bookbag image"
    shell: "{{ item }}"
    args:
      chdir: "{{ bookbag_dir }}/{{ bookbag_build_dir }}"
    loop:
      - "oc project lab-instructions"
      - "oc process -f build-template.yaml -p GIT_REPO='{{ bookbag_repo }}' | oc apply -f -"
      - "oc start-build bookbag --follow --from-dir={{ bookbag_dir }}"

  - name: "Deploying bookbag image"
    shell: "oc process -f deploy-template.yaml -p WORKSHOP_VARS='{{ ocp4_info | to_json }}' | oc apply -f -"
    args:
      chdir: "{{ bookbag_dir }}/{{ bookbag_build_dir }}"

  - name: "Read bookbag route"
    shell: "oc get route -n lab-instructions bookbag -o go-template='{{ '{{' }} .spec.host {{ '}}' }}{{ '{{' }} println {{ '}}' }}'"
    register: output

  - debug:
      msg: "Route to bookbag : {{ output.stdout }}"
